version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level:
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: './logs/general.log'
loggers:
  simple:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console, file]
